import { useState } from 'react';
import { useNavigate, useLocation, useParams } from 'react-router-dom';
import { Car, Bike, Truck, CreditCard, Smartphone, Clock, Check, ChevronLeft, Minus, Plus } from 'lucide-react';
import { Button } from '@/app/components/ui/button';
import { Input } from '@/app/components/ui/input';
import { Label } from '@/app/components/ui/label';
import { Card } from '@/app/components/ui/card';
import { RadioGroup, RadioGroupItem } from '@/app/components/ui/radio-group';
import { Separator } from '@/app/components/ui/separator';
import { Slider } from '@/app/components/ui/slider';
import { useApp } from '@/context/AppContext';
import type { VehicleType, PaymentMethod } from '@/types';
import { toast } from 'sonner';
import QRCode from 'react-qr-code';

export function BookingVehicle() {
  const navigate = useNavigate();
  const location = useLocation();
  const { id } = useParams();
  const { getFacilityById, createBooking, user } = useApp();

  const facility = getFacilityById(id!);
  const { slotId } = location.state || {}; // In real app, re-fetch or ensure slot logic

  const [vehicleNumber, setVehicleNumber] = useState('');
  const [vehicleType, setVehicleType] = useState<VehicleType>('car');
  const [duration, setDuration] = useState(2); // Default 2 hours
  const [paymentMethod, setPaymentMethod] = useState<PaymentMethod>('upi');
  const [isProcessing, setIsProcessing] = useState(false);

  // Mock Pricing Logic
  const pricePerHour = 60;
  const totalAmount = pricePerHour * duration;

  const handleConfirmBooking = async () => {
    if (!vehicleNumber) {
      toast.error('Please enter your vehicle number');
      document.getElementById('vehicle-input')?.focus();
      return;
    }

    setIsProcessing(true);

    try {
      // const booking = createBooking({ ... }) -> await createBooking
      const booking = await createBooking({
        customerId: user!.id,
        facilityId: id!,
        slotId: slotId || '', // Check valid slotId later
        vehicleNumber: vehicleNumber.toUpperCase(),
        vehicleType,
        entryTime: new Date().toISOString(),
        duration,
        amount: totalAmount,
        paymentMethod,
        status: 'active',
        qrCode: '', // Will be generated by backend
      });

      toast.success('Booking Successful!');
      navigate('/customer/booking/success', { state: { booking } });
    } catch (error) {
      toast.error('Booking failed. Please try again.');
    } finally {
      setIsProcessing(false);
    }
  };

  return (
    <div className="min-h-screen bg-gray-50 pb-32 pt-16">
      {/* Header */}
      <div className="bg-white px-4 py-4 fixed top-0 left-0 right-0 z-10 border-b flex items-center">
        <Button variant="ghost" size="icon" onClick={() => navigate(-1)} className="mr-2">
          <ChevronLeft className="w-6 h-6" />
        </Button>
        <h1 className="text-lg font-bold">Confirm Booking</h1>
      </div>

      <div className="max-w-2xl mx-auto px-4 mt-6 space-y-6">

        {/* Facility Summary */}
        <Card className="p-4 flex gap-4 items-center">
          <div className="w-16 h-16 bg-gray-200 rounded-lg overflow-hidden shrink-0">
            <img src={facility?.images[0]} alt="" className="w-full h-full object-cover" />
          </div>
          <div>
            <h3 className="font-bold text-gray-900">{facility?.name}</h3>
            <p className="text-sm text-gray-500">{facility?.address}</p>
          </div>
        </Card>

        {/* Vehicle Details */}
        <div className="space-y-4">
          <h3 className="font-bold text-lg">Vehicle Details</h3>
          <Card className="p-4 space-y-4">
            <div>
              <Label className="text-xs text-gray-500 uppercase tracking-wide">Vehicle Number</Label>
              <Input
                id="vehicle-input"
                placeholder="Ex: MH 02 AB 1234"
                value={vehicleNumber}
                onChange={(e) => setVehicleNumber(e.target.value)}
                className="mt-1 h-12 text-lg font-bold uppercase placeholder:font-normal placeholder:capitalize"
              />
            </div>

            <div>
              <Label className="text-xs text-gray-500 uppercase tracking-wide mb-2 block">Vehicle Type</Label>
              <div className="grid grid-cols-4 gap-2">
                {(['bike', 'scooter', 'car', 'truck'] as VehicleType[]).map((type) => (
                  <button
                    key={type}
                    onClick={() => setVehicleType(type)}
                    className={`flex flex-col items-center justify-center p-2 rounded-lg border-2 transition-all ${vehicleType === type
                      ? 'border-indigo-600 bg-indigo-50 text-indigo-700'
                      : 'border-transparent bg-gray-100 text-gray-600 hover:bg-gray-200'
                      }`}
                  >
                    {type === 'bike' && <Bike className="w-6 h-6 mb-1" />}
                    {type === 'scooter' && <Bike className="w-6 h-6 mb-1" />}
                    {type === 'car' && <Car className="w-6 h-6 mb-1" />}
                    {type === 'truck' && <Truck className="w-6 h-6 mb-1" />}
                    <span className="text-[10px] font-bold uppercase">{type}</span>
                  </button>
                ))}
              </div>
            </div>
          </Card>
        </div>

        {/* Duration Selection */}
        <div className="space-y-4">
          <h3 className="font-bold text-lg">Duration</h3>
          <Card className="p-6">
            <div className="flex justify-between items-center mb-6">
              <div className="text-center">
                <span className="text-3xl font-black text-indigo-600">{duration}</span>
                <span className="text-sm text-gray-500 ml-1">hours</span>
              </div>
              <div className="text-right">
                <p className="text-xs text-gray-500 uppercase font-bold">Est. Cost</p>
                <p className="text-2xl font-black text-gray-900">₹{totalAmount}</p>
              </div>
            </div>

            <div className="flex items-center gap-4">
              <Button variant="outline" size="icon" onClick={() => setDuration(Math.max(1, duration - 1))}>
                <Minus className="w-4 h-4" />
              </Button>
              <Slider
                value={[duration]}
                onValueChange={(v) => setDuration(v[0])}
                min={1}
                max={24}
                step={1}
                className="flex-1"
              />
              <Button variant="outline" size="icon" onClick={() => setDuration(Math.min(24, duration + 1))}>
                <Plus className="w-4 h-4" />
              </Button>
            </div>
          </Card>
        </div>

        {/* Payment Method */}
        <div className="space-y-4">
          <h3 className="font-bold text-lg">Payment Method</h3>
          <div className="space-y-2">
            <PaymentOption
              id="upi"
              title="UPI"
              icon={Smartphone}
              selected={paymentMethod}
              onSelect={() => setPaymentMethod('upi')}
            />
            <PaymentOption
              id="card"
              title="Credit/Debit Card"
              icon={CreditCard}
              selected={paymentMethod}
              onSelect={() => setPaymentMethod('card')}
            />
            <PaymentOption
              id="pay-at-exit"
              title="Pay at Location"
              icon={Clock}
              selected={paymentMethod}
              onSelect={() => setPaymentMethod('pay-at-exit')}
            />
          </div>
        </div>
      </div>

      {/* Fixed Bottom Button */}
      <div className="fixed bottom-0 left-0 right-0 p-4 bg-white border-t z-20 pb-safe">
        <div className="max-w-2xl mx-auto flex gap-4 items-center">
          <div className="flex-1">
            <p className="text-xs text-gray-500 font-bold uppercase">Total to pay</p>
            <p className="text-2xl font-black">₹{totalAmount}</p>
          </div>
          <Button
            onClick={handleConfirmBooking}
            disabled={isProcessing}
            className="h-14 px-8 rounded-xl text-lg font-bold bg-indigo-600 hover:bg-indigo-700 shadow-lg shadow-indigo-200 min-w-[200px]"
          >
            {isProcessing ? 'Processing...' : 'Pay & Book'}
          </Button>
        </div>
      </div>
    </div>
  );
}

function PaymentOption({ id, title, icon: Icon, selected, onSelect }: any) {
  const isSelected = selected === id;
  return (
    <div
      onClick={onSelect}
      className={`flex items-center p-4 rounded-xl border-2 cursor-pointer transition-all ${isSelected ? 'border-indigo-600 bg-indigo-50' : 'border-gray-100 bg-white hover:border-gray-200'
        }`}
    >
      <div className={`w-10 h-10 rounded-full flex items-center justify-center mr-3 ${isSelected ? 'bg-indigo-200 text-indigo-700' : 'bg-gray-100 text-gray-500'}`}>
        <Icon className="w-5 h-5" />
      </div>
      <span className={`font-bold ${isSelected ? 'text-indigo-900' : 'text-gray-700'}`}>{title}</span>
      {isSelected && <Check className="w-5 h-5 text-indigo-600 ml-auto" />}
    </div>
  );
}

// Keeping this as a placeholder or alias if needed, but routing should mainly use BookingVehicle
export function BookingPayment() {
  return null;
}

export function BookingSuccess() {
  const navigate = useNavigate();
  const location = useLocation();
  const { booking } = location.state || {};
  const { getFacilityById } = useApp();

  const facility = getFacilityById(booking?.facilityId);

  if (!booking) {
    navigate('/customer/search');
    return null;
  }

  return (
    <div className="min-h-screen bg-gray-50 pt-16 flex flex-col items-center justify-center p-4">
      <Card className="w-full max-w-md overflow-hidden shadow-xl rounded-3xl relative">
        <div className="bg-emerald-500 p-6 text-center text-white pb-12">
          <div className="w-16 h-16 bg-white/20 rounded-full flex items-center justify-center mx-auto mb-4 backdrop-blur-sm">
            <Check className="w-8 h-8 text-white" />
          </div>
          <h1 className="text-2xl font-black">Booking Confirmed!</h1>
          <p className="text-emerald-50">Your space is reserved</p>
        </div>

        <div className="px-6 -mt-8">
          <div className="bg-white rounded-2xl p-4 shadow-sm border border-gray-100">
            <div className="flex justify-center py-4">
              <QRCode value={booking.qrCode} size={150} />
            </div>
            <div className="text-center border-t border-dashed border-gray-200 pt-4 mt-2">
              <p className="text-xs text-gray-400 uppercase tracking-widest font-bold mb-1">Pass Code</p>
              <p className="text-xl font-mono font-black text-gray-800 tracking-wider">#{booking.id.slice(-6).toUpperCase()}</p>
            </div>
          </div>
        </div>

        <div className="p-6 space-y-4">
          <div className="space-y-2">
            <div className="flex justify-between text-sm">
              <span className="text-gray-500">Location</span>
              <span className="font-bold text-gray-900">{facility?.name}</span>
            </div>
            <div className="flex justify-between text-sm">
              <span className="text-gray-500">Vehicle</span>
              <span className="font-bold text-gray-900">{booking.vehicleNumber}</span>
            </div>
            <div className="flex justify-between text-sm">
              <span className="text-gray-500">Time</span>
              <span className="font-bold text-gray-900">{new Date(booking.entryTime).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })} ({booking.duration}h)</span>
            </div>
          </div>

          <div className="flex gap-3 pt-4">
            <Button variant="outline" className="flex-1" onClick={() => navigate('/customer/search')}>
              Home
            </Button>
            <Button className="flex-1 bg-indigo-600 hover:bg-indigo-700" onClick={() => navigate('/customer/tickets')}>
              My Ticket
            </Button>
          </div>
        </div>

        {/* Decorative Circles */}
        <div className="absolute top-0 left-0 w-full h-2 bg-emerald-600/20" />
      </Card>

      <p className="text-xs text-gray-400 mt-6 text-center max-w-xs">
        Show this QR code at the entrance scanner to access your parking spot.
      </p>
    </div>
  );
}
